<?php require_once('includes/global/config.php'); ?>
<?php require_once('includes/global/functions.php'); ?>
<?php require_once('includes/global/head.php'); ?>
<?php require_once('includes/sections/masthead.php'); ?>
<?php require_once('includes/sections/services.php'); ?>
<?php require_once('includes/sections/portfolio.php'); ?>
<?php require_once('includes/sections/about.php'); ?>
<?php require_once('includes/sections/contact.php'); ?>
<?php require_once('includes/global/foot.php'); ?>